name: test

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: create client_secret.json
        env:
          GOOGLE_SHEET_CLIENT_SECRET: ${{ secrets.GOOGLE_SHEET_CLIENT_SECRET }}
        run: |
          echo '${{ secrets.GOOGLE_SHEET_CLIENT_SECRET }}' >> client_secret.json
      - name: cat client_secret.json
        run: cat client_secret.json
      - name: create translate.json file
        run: node ./index.js
      - name: cat translate.json
        run: cat translate.json
